language: go
go: '1.14.x'
addons:
  apt:
    packages:
    - snapd
env:
  - PATH=/snap/bin:$PATH
install:
  - make setup
  - sudo snap install snapcraft --classic
script: make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test -n "$TRAVIS_TAG" && openssl aes-256-cbc -K $encrypted_dbda2be8d01e_key -iv $encrypted_dbda2be8d01e_iv -in snap.login.enc -out snap.login -d && snapcraft login --with snap.login
notifications:
  email: false
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
